kafka:
  nodeId: 1
  port: 9092
  clusterId: "MkU3OEVBNTcwNTJENDM2Qk"  # generate once
  storage:
    type: emptyDir
backend:
  image: manufreit/sd-backend:latest
  port: 8000
simulator:
  image: manufreit/sd-simulator:latest
  gpxFolder: /app/gpx
frontend:
  image: manufreit/sd-frontend:latest
  assetsPath: /usr/share/nginx/html/assets
  gpxPath: /usr/share/nginx/html/gpx

