backend:
  enabled: true
  image: manufreit/sd-backend:v22-c4c677a
  port: 30015
simulator:
  enabled: true
  image: manufreit/sd-simulator:v22-c4c677a
  port: 30035
  gpxFolder: /app/gpx
frontend:
  enabled: true
  image: manufreit/sd-frontend:v22-c4c677a
  port: 30025
  assetsPath: /usr/share/nginx/html/assets
  gpxPath: /usr/share/nginx/html/gpx
rabbitmq:
  enabled: true
  host: rabbitmq
  port: 5672
  managementPort: 15672
  user: grupo5
  password: z1x2c3v4b5n6
