backend:
  enabled: true
  image: manufreit/sd-backend:v44-6c3d696
  port: 30015
simulator:
  enabled: true
  image: manufreit/sd-simulator:v46-a130c1d
  port: 30035
  gpxFolder: /app/gpx
frontend:
  enabled: true
  image: manufreit/sd-frontend:v45-d942317
  port: 30025
  assetsPath: /usr/share/nginx/html/assets
  gpxPath: /usr/share/nginx/html/gpx
rabbitmq:
  enabled: false
  host: rabbitmq-cluster.rabbitmq-system.svc.cluster.local
  port: 5672
  managementPort: 15672
  user: grupo5
  password: z1x2c3v4b5n6
  vhost: grupo5
