backend:
  image: manufreit/sd-backend:latest
  port: 8000
simulator:
  image: manufreit/sd-simulator:latest
  gpxFolder: /app/gpx
frontend:
  image: manufreit/sd-frontend:latest
  assetsPath: /usr/share/nginx/html/assets
  gpxPath: /usr/share/nginx/html/gpx
rabbitmq:
  host: rabbitmq
  port: 5672
  managementPort: 15672
  user: guest
  password: guest
