apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: sd
  labels:
    app: backend
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - sd
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
