name: backend-env
channels:
  - conda-forge
dependencies:
  - python=3.10           # or 3.10 if you prefer
  - pip
  - pytest
  - aio-pika
  - gpxpy
  - requests
  - pip:
      - fastapi==0.111.1
      - uvicorn[standard]==0.27.0
      - pydantic==2.6.0
      - pytest-asyncio==0.22.0